version: '3.8'

services:
  # ---------- Admin (Go) ----------
  admin:
    build:
      context: .
      dockerfile: Dockerfile.admin
    ports:
      - "8080:8080"

  # ---------- Load Balancer (Go) ----------
  loadbalancer:
    build:
      context: .
      dockerfile: Dockerfile.loadbalancer
    ports:
      - "8000:8000"
    depends_on:
      - admin
      - rabbitmq
    environment:
      - ADMIN_BASE=http://admin:8080    # 若你改成用 env 取值

  # ---------- RabbitMQ ----------
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"

  # ---------- 4 simple Nginx backends ----------
  backend1: &backend
    image: nginx:1.25-alpine
    environment:
      - SERVER_NAME=r1
    volumes:
      - ./nginx/backend.conf.template:/etc/nginx/templates/backend.conf.template:ro

  backend2:
    <<: *backend
    environment:
      - SERVER_NAME=r2

  backend3:
    <<: *backend
    environment:
      - SERVER_NAME=r3

  backend4:
    <<: *backend
    environment:
      - SERVER_NAME=r4
